source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KMQToolKit_Example', :exclusive => true do
  pod "KMQToolKit", :path => "../"
end

target 'KMQToolKit_Tests', :exclusive => true do
  pod "KMQToolKit", :path => "../"

  
end
